### ISSUE TITLE
Are there any Windows executable files that have been compiled? because I couldn't compile successfully.

### ISSUE THREAD

**Issue by fblosee** [depler/curl-impersonate-win#1]
Are there any executables that have been compiled and are suitable for PHP on Windows?
![V$V3OY$DG70IYZ`KSZ@H{)J](https://user-images.githubusercontent.com/57052377/189561250-fd2349bd-85f2-494f-9888-4e986ac28a6b.png)

**Comment by depler** [comment]
Yes, executables are located inside release archive: https://github.com/depler/curl-impersonate-win/releases/tag/7.84.0
