### ISSUE TITLE
URL Parameters don't work

### ISSUE THREAD

**Issue by barkoder** [depler/curl-impersonate-win#13]
`curl_chrome110.bat -s 'https://example.org/urlparam&urlparam1=1&urlparam2=2'`

    'urlparam1' is not recognized as an internal or external command,
    operable program or batch file.
    'urlparam2' is not recognized as an internal or external command,
    operable program or batch file.

**Comment by norbis3** [comment]
Hi, remove %~dp0 from bat. 

`@echo off
curl.exe --config config/chrome110.config --header @config/chrome110.header %*`

**Comment by barkoder** [comment]
Hi @norbis3 thanks, but that doesn't work either.

Firstly I'd like to mention that I had to slightly modifiy my `curl_chrome*.bat` files

Because the default gives me these errors on both cygwin/mintty and cmd.exe

    curl: cannot read config from 'config/chrome110.config'
    curl: option --config: error encountered when reading a file
    curl: try 'curl --help' or 'curl --manual' for more information

So I had to declare absolute paths to the configs to get curl-impersonate working.

`%~dp0curl.exe --config c:/curl-impersonate-win/config/chrome110.config --header @c:/curl-impersonate-win/config/chrome110.header %*`

Anyway, stripping out the `%~dp0` from that still gives a lot of warnings.

`C:/curl-impersonate-win/curl_chrome110.bat -s https://example.com`

prints the page

    Warning: c:/curl-impersonate-win/config/chrome110.config:4: warning:
    Warning: '--http2-no-server-push' is unknown
    Warning: --npn is no longer supported
    Warning: c:/curl-impersonate-win/config/chrome110.config:9: warning:
    Warning: '--alps' is unknown
    Warning: c:/curl-impersonate-win/config/chrome110.config:10: warning:
    Warning: '--tls-permute-extensions' is unknown
    Warning: c:/curl-impersonate-win/config/chrome110.config:11: warning:
    Warning: '--cert-compression' is unknown

Testing on example URL with parameters

On Cygwin/bash/mintty,

`"C:/curl-impersonate-win/curl_chrome110.bat" -s 'https://example.com/search?q=test&urlparam1=value1&urlparam2=value2'`

Prints example.com

and then

    Warning: c:/curl-impersonate-win/config/chrome110.config:4: warning:
    Warning: '--http2-no-server-push' is unknown
    Warning: --npn is no longer supported
    Warning: c:/curl-impersonate-win/config/chrome110.config:9: warning:
    Warning: '--alps' is unknown
    Warning: c:/curl-impersonate-win/config/chrome110.config:10: warning:
    Warning: '--tls-permute-extensions' is unknown
    Warning: c:/curl-impersonate-win/config/chrome110.config:11: warning:
    Warning: '--cert-compression' is unknown
    'urlparam1' is not recognized as an internal or external command, operable program or batch file.
    'urlparam2' is not recognized as an internal or external command, operable program or batch file.

On cmd.exe,

I get the same warnings but just without,

    'urlparam1' is not recognized as an internal or external command, operable program or batch file.
    'urlparam2' is not recognized as an internal or external command, operable program or batch file.

**Comment by TalkLounge** [comment]
Can confirm this. Removing %~dp0 from the bat doesn't help.
Also you need to call the bat directly in the folder otherwise the config bugs. ./curl_chrome110.bat works, ./myFolder/curl_chrome110.bat doesn't.

**Comment by depler** [comment]
In case of use curl elsewhere except console - please don't use bat scripts. Use raw curl.exe syntax instead.
