### ISSUE TITLE
there is no 'curl' and 'boringssl' directory

### ISSUE THREAD

**Issue by bintesztelo** [depler/curl-impersonate-win#14]
How to clone this repository? I have aproblem with that:
"Clone this repository with --recursive attribute to get BoringSSL and Curl submodules."

Just copy the "boringssl_original" to "boringssl"?

**Comment by nindogo** [comment]
> "Clone this repository with --recursive attribute to get BoringSSL and Curl submodules."

`git clone --recursive https://github.com/depler/curl-impersonate-win.git`

**Comment by depler** [comment]
Please see readme page
