### ISSUE TITLE
New Build

### ISSUE THREAD

**Issue by STRATZ-Ken** [depler/curl-impersonate-win#17]
I created a new build.  Did curl.exe --version and got 

Release-Date: 2023-10-11
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

I guess my question is, do I have to complete other steps to pull the latest from https://github.com/lwthiker/curl-impersonate/releases or is that done automatically? 

Looking for WebSocket support.

**Comment by depler** [comment]
Updated source code, web socket is now supported

**Comment by STRATZ-Ken** [comment]
Thanks, can you provide a small TLDR on how to use WebSocket. How to connect, how to send data, etc?
