### ISSUE TITLE
GitHub actions build workflow

### ISSUE THREAD

**Issue by yifeikong** [depler/curl-impersonate-win#9]
Is it possible to automatically build new binaries with github actions? I see that windows machines are available. With that implemented, the packages can be up-to-date with upstream curl-impersonate and no one need to build themselves.

**Comment by depler** [comment]
The upstream repository does not contain any code updates since September 2022. Sorry, I don't really see the reason to overcomlicate things.

**Comment by yifeikong** [comment]
Sure. But they just updated today...
